/*
 * Copyright 2015-2025 Endre Stølsvik
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.mats3.test.jupiter;

import java.util.List;
import java.util.Optional;

import jakarta.inject.Inject;

import org.junit.jupiter.api.extension.AfterEachCallback;
import org.junit.jupiter.api.extension.BeforeEachCallback;
import org.junit.jupiter.api.extension.ExtensionContext;
import org.junit.jupiter.api.extension.RegisterExtension;

import io.mats3.MatsEndpoint.ProcessSingleLambda;
import io.mats3.MatsEndpoint.ProcessTerminatorLambda;
import io.mats3.MatsFactory;
import io.mats3.test.MatsTestEndpoint;
import io.mats3.test.MatsTestEndpoint.IEndpoint;
import io.mats3.test.MatsTestEndpoint.IEndpointWithState;
import io.mats3.test.MatsTestEndpoint.ITerminator;
import io.mats3.test.MatsTestEndpoint.ITerminatorWithState;
import io.mats3.test.MatsTestEndpoint.Message;
import io.mats3.test.abstractunit.AbstractMatsTestEndpoint;

/**
 * JUnit 5 (Jupiter) factories for {@link MatsTestEndpoint}. You get instances by using the different
 * {@link #createEndpoint(String, Class, Class)} methods, and the (non-static) field must annotated with
 * {@link RegisterExtension}. Read the JavaDoc at {@link MatsTestEndpoint} for more information.
 *
 * @see MatsTestEndpoint
 */
public class Extension_MatsTestEndpoints {

    /**
     * Creates a JUnit Extension for a single-staged endpoint whose processor is <i>not</i> defined at start. Sets it up
     * on Jupiter lifecycle 'beforeEach' and tears it down on 'afterEach'. <b>Notice that a {@link MatsFactory} and
     * {@link Endpoint#setProcessLambda(ProcessSingleLambda) process lambda} must be set before it is usable!</b> In a
     * Spring environment, you should probably employ the <code>@SpringInjectRulesAndExtensions</code> to set the
     * MatsFactory automagically. In a "pure Java" environment, consider the convenience overloads like
     * {@link #createEndpoint(Extension_Mats, String, Class, Class) createEndpoint(MATS, endpointId, replyClass,
     * stateClass, incomingClass)} to easily supply the corresponding <code>{@literal @Extension}</code>
     * {@link Extension_Mats} for fetching the <code>MatsFactory</code>.
     * <p>
     * <b>You need to set the process lambda via {@link Endpoint#setProcessLambda(ProcessSingleLambda)
     * setProcessLambda(lambda)}</b> - typically inside the <code>{@literal @Test}</code> method - before sending
     * messages to it. The await methods will throw an <code>IllegalStateException</code> if not set.
     * <p>
     * Should there be no need for a processor, use {@link #createTerminator(String, Class, Class)} instead.
     * 
     * @param endpointId
     *            of the endpoint.
     * @param replyMsgClass
     *            the class of the reply message generated by this endpoint.
     * @param incomingMsgClass
     *            the incoming message class for this endpoint.
     * @return {@link IEndpoint}
     * @see #createTerminator(String, Class, Class)
     */
    public static <R, I> Endpoint<R, I> createEndpoint(String endpointId, Class<R> replyMsgClass,
            Class<I> incomingMsgClass) {
        return new EndpointImpl<>(endpointId, replyMsgClass, incomingMsgClass);
    }

    /**
     * Expanded version of {@link #createEndpoint(String, Class, Class)} which also allows for the specification of a
     * state class for the "initial state" concept when sending message or requests to the endpoint.
     *
     * @param endpointId
     *            of the endpoint.
     * @param replyMsgClass
     *            the class of the reply message generated by this endpoint.
     * @param stateClass
     *            the class of the state object for this endpoint.
     * @param incomingMsgClass
     *            the incoming message class for this endpoint.
     * @return {@link IEndpointWithState}
     */
    public static <R, S, I> EndpointWithState<R, S, I> createEndpoint(String endpointId, Class<R> replyMsgClass,
            Class<S> stateClass, Class<I> incomingMsgClass) {
        return new EndpointWithStateImpl<>(endpointId, replyMsgClass, stateClass, incomingMsgClass);
    }

    /**
     * Creates a Terminator, i.e. an endpoint which does not reply, and thus does not require reply class, and where the
     * process lambda is optional. Useful for mock endpoints where one is simply interested in the incoming message.
     *
     * @param endpointId
     *            of the endpoint.
     * @param incomingMsgClass
     *            the incoming message class for this endpoint.
     * @return {@link ITerminator}
     */
    public static <I> Terminator<I> createTerminator(String endpointId, Class<I> incomingMsgClass) {
        return new TerminatorImpl<>(endpointId, incomingMsgClass);
    }

    /**
     * Expanded version of {@link #createTerminator(String, Class)}, which also allows for the specification of a state
     * class for whatever state was provided in the initiation for the Terminator.
     *
     * @param endpointId
     *            of the endpoint.
     * @param stateClass
     *            the class of the state object for this endpoint.
     * @param incomingMsgClass
     *            the incoming message class for this endpoint.
     * @return {@link ITerminator}
     */
    public static <S, I> TerminatorWithState<S, I> createTerminator(String endpointId, Class<S> stateClass,
            Class<I> incomingMsgClass) {
        return new TerminatorWithStateImpl<>(endpointId, stateClass, incomingMsgClass) {
        };
    }

    /**
     * Convenience variant of {@link #createEndpoint(String, Class, Class) createEndpoint(endpointId, replyClass,
     * incomingClass)} taking a {@link Extension_Mats} as first argument for fetching the {@link MatsFactory}, for use
     * in "pure Java" environments (read as: non-Spring).
     */
    public static <R, I> Endpoint<R, I> createEndpoint(Extension_Mats matsRule, String endpointId,
            Class<R> replyMsgClass,
            Class<I> incomingMsgClass) {
        EndpointImpl<R, I> rule_matsEndpoint = new EndpointImpl<>(endpointId, replyMsgClass, incomingMsgClass);
        // Set MatsFactory from the supplied Rule_Mats
        rule_matsEndpoint.setMatsFactory(matsRule.getMatsFactory());
        return rule_matsEndpoint;
    }

    /**
     * Convenience variant of {@link #createEndpoint(String, Class, Class, Class) createEndpoint(endpointId, replyClass,
     * stateClass, incomingClass)} taking a {@link Extension_Mats} as first argument for fetching the
     * {@link MatsFactory}, for use in "pure Java" environments (read as: non-Spring).
     */
    public static <R, S, I> EndpointWithState<R, S, I> createEndpoint(Extension_Mats matsRule, String endpointId,
            Class<R> replyMsgClass, Class<S> stateClass, Class<I> incomingMsgClass) {
        EndpointWithStateImpl<R, S, I> rule_matsEndpoint = new EndpointWithStateImpl<>(endpointId, replyMsgClass,
                stateClass, incomingMsgClass);
        // Set MatsFactory from the supplied Rule_Mats
        rule_matsEndpoint.setMatsFactory(matsRule.getMatsFactory());
        return rule_matsEndpoint;
    }

    /**
     * Convenience variant of {@link #createTerminator(String, Class) createTerminator(endpointId, incomingClass)}
     * taking a {@link Extension_Mats} as first argument for fetching the {@link MatsFactory}, for use in "pure Java"
     * environments (read as: non-Spring).
     */
    public static <I> Terminator<I> createTerminator(Extension_Mats matsRule,
            String endpointId, Class<I> incomingMsgClass) {
        TerminatorImpl<I> iTerminatorNoState = new TerminatorImpl<>(endpointId, incomingMsgClass);
        iTerminatorNoState.setMatsFactory(matsRule.getMatsFactory());
        return iTerminatorNoState;
    }

    /**
     * Convenience variant of {@link #createTerminator(String, Class, Class) createTerminator(endpointId, stateClass,
     * incomingClass)} taking a {@link Extension_Mats} as first argument for fetching the {@link MatsFactory}, for use
     * in "pure Java" environments (read as: non-Spring).
     */
    public static <S, I> TerminatorWithState<S, I> createTerminator(Extension_Mats matsRule,
            String endpointId, Class<S> stateClass, Class<I> incomingMsgClass) {
        TerminatorWithStateImpl<S, I> siTerminator = new TerminatorWithStateImpl<>(endpointId, stateClass,
                incomingMsgClass);
        siTerminator.setMatsFactory(matsRule.getMatsFactory());
        return siTerminator;
    }

    // ================================================================================================================
    // Interface overrides
    // ================================================================================================================

    public interface Endpoint<R, I> extends IEndpoint<R, I>, BeforeEachCallback, AfterEachCallback {
        Endpoint<R, I> setProcessLambda(ProcessSingleLambda<R, I> processLambda);

        @Override
        Endpoint<R, I> setMatsFactory(MatsFactory matsFactory);
    }

    public interface EndpointWithState<R, S, I> extends IEndpointWithState<R, S, I>, BeforeEachCallback,
            AfterEachCallback {
        EndpointWithState<R, S, I> setProcessLambda(ProcessSingleStateLambda<R, S, I> processLambda);

        @Override
        EndpointWithState<R, S, I> setMatsFactory(MatsFactory matsFactory);
    }

    public interface Terminator<I> extends ITerminator<I>, BeforeEachCallback, AfterEachCallback {
        Terminator<I> setProcessLambda(ProcessTerminatorNoStateLambda<I> processLambda);

        @Override
        Terminator<I> setMatsFactory(MatsFactory matsFactory);
    }

    public interface TerminatorWithState<S, I> extends ITerminatorWithState<S, I>, BeforeEachCallback,
            AfterEachCallback {
        TerminatorWithState<S, I> setProcessLambda(ProcessTerminatorLambda<S, I> processLambda);

        @Override
        TerminatorWithState<S, I> setMatsFactory(MatsFactory matsFactory);
    }

    // ================================================================================================================
    // Impls
    // ================================================================================================================

    private static class EndpointImpl<R, I> extends JupiterCommonsImpl<R, Void, I>
            implements Endpoint<R, I> {

        EndpointImpl(String endpointId, Class<R> replyMsgClass, Class<I> incomingMsgClass) {
            super(endpointId, replyMsgClass, Void.class, incomingMsgClass);
        }

        @Override
        public Endpoint<R, I> setProcessLambda(ProcessSingleLambda<R, I> lambda) {
            _processLambda = lambda;
            return this;
        }

        @Inject
        @Override
        public Endpoint<R, I> setMatsFactory(MatsFactory matsFactory) {
            _matsFactory = matsFactory;
            return this;
        }
    }

    private static class EndpointWithStateImpl<R, S, I> extends JupiterCommonsImpl<R, S, I>
            implements EndpointWithState<R, S, I> {

        EndpointWithStateImpl(String endpointId, Class<R> replyMsgClass, Class<S> stateClass,
                Class<I> incomingMsgClass) {
            super(endpointId, replyMsgClass, stateClass, incomingMsgClass);
        }

        @Override
        public EndpointWithState<R, S, I> setProcessLambda(ProcessSingleStateLambda<R, S, I> lambda) {
            _processLambda = lambda;
            return this;
        }

        @Inject
        @Override
        public EndpointWithState<R, S, I> setMatsFactory(MatsFactory matsFactory) {
            _matsFactory = matsFactory;
            return this;
        }
    }

    private static class TerminatorImpl<I> extends JupiterCommonsImpl<Void, Void, I>
            implements Terminator<I> {

        TerminatorImpl(String endpointId, Class<I> incomingMsgClass) {
            super(endpointId, void.class, void.class, incomingMsgClass);
        }

        @Override
        public Terminator<I> setProcessLambda(ProcessTerminatorNoStateLambda<I> lambda) {
            _processLambda = lambda;
            return this;
        }

        @Inject
        @Override
        public Terminator<I> setMatsFactory(MatsFactory matsFactory) {
            _matsFactory = matsFactory;
            return this;
        }
    }

    private static class TerminatorWithStateImpl<S, I> extends JupiterCommonsImpl<Void, S, I>
            implements TerminatorWithState<S, I> {

        TerminatorWithStateImpl(String endpointId, Class<S> stateClass, Class<I> incomingMsgClass) {
            super(endpointId, Void.class, stateClass, incomingMsgClass);
        }

        @Override
        public TerminatorWithState<S, I> setProcessLambda(ProcessTerminatorLambda<S, I> lambda) {
            _processLambda = lambda;
            return this;
        }

        @Inject
        @Override
        public TerminatorWithState<S, I> setMatsFactory(MatsFactory matsFactory) {
            _matsFactory = matsFactory;
            return this;
        }
    }

    /**
     * Common base class for the all the impls.
     *
     * @see EndpointImpl
     * @see EndpointWithStateImpl
     * @see TerminatorImpl
     * @see TerminatorWithStateImpl
     */
    private static abstract class JupiterCommonsImpl<R, S, I> extends AbstractMatsTestEndpoint<R, S, I>
            implements BeforeEachCallback, AfterEachCallback {

        protected JupiterCommonsImpl(String endpointId, Class<R> replyMsgClass, Class<S> stateClass,
                Class<I> incomingMsgClass) {
            super(endpointId, replyMsgClass, stateClass, incomingMsgClass);
        }

        public Message<S, I> awaitInvocation() {
            assertProcessLambdaSetIfRelevant();
            return super.awaitInvocation();
        }

        public Message<S, I> awaitInvocation(long millisToWait) {
            assertProcessLambdaSetIfRelevant();
            return super.awaitInvocation(millisToWait);
        }

        public List<Message<S, I>> awaitInvocations(int expectedNumberOfIncomingMsgs) {
            assertProcessLambdaSetIfRelevant();
            return super.awaitInvocations(expectedNumberOfIncomingMsgs);
        }

        public List<Message<S, I>> awaitInvocations(int expectedNumberOfIncomingMsgs, long millisToWait) {
            assertProcessLambdaSetIfRelevant();
            return super.awaitInvocations(expectedNumberOfIncomingMsgs, millisToWait);
        }

        private void assertProcessLambdaSetIfRelevant() {
            // ?: Is it a Terminator?
            if ((this instanceof ITerminator) || (this instanceof ITerminatorWithState)) {
                // -> Yes, and Terminators do not need process lambda set.
                return;
            }
            if (_processLambda == null) {
                throw new IllegalStateException("The process lambda has not been set for test endpoint '"
                        + _endpoint.getEndpointConfig().getEndpointId() + "', and it is not a Terminator-type."
                        + " Please set it using setProcessLambda() before awaitInvocation, or use a Terminator-type.");
            }
        }

        // ================== Jupiter LifeCycle =======================================================================

        public void beforeEach(ExtensionContext context) {
            // ?: Do we have the MatsFactory set yet?
            if (_matsFactory == null) {
                // -> No, so let's see if we can find it in the ExtensionContext (throws if not).
                Optional<Extension_Mats> matsFromContext = Extension_Mats.findFromContext(context);
                if (matsFromContext.isPresent()) {
                    _matsFactory = matsFromContext.get().getMatsFactory();
                }
                else {
                    throw new IllegalStateException("MatsFactory is not set. Didn't find Extension_Mats in"
                            + " ExtensionContext, so couldn't get it from there either. Either set it explicitly"
                            + " using setMatsFactory(matsFactory), or use Extension_Mats (which adds itself to the"
                            + " ExtensionContext), and ensure that it is initialized before this"
                            + " Extension_MatsEndpoints field.");
                }
            }
            super.before();
        }

        public void afterEach(ExtensionContext context) {
            super.after();
        }
    }
}
